### ISSUE TITLE
data loading problem

### ISSUE THREAD

**Issue by hanzh346** [clintonjwang/sitgan#1]
Hello,

Nice work and good paper!

I got an issue when I load my datalist into batch, here is the get_datalist I defined:

def get_datalists(args):

    # Load the xlsx file into a pandas DataFrame
    df = pd.read_excel("src/spatial-intensity-transforms/HABS/ages_of_subjects.xlsx")

    datalist = []

    # Iterate over the DataFrame
    for index, row in df.iterrows():
       # Construct the folder name
        folder_name = os.path.join("src/spatial-intensity-transforms/HABS/",str(row['sub_id']).split("P_")[1])

        # Check if the folder exists
        if os.path.isdir(folder_name):

            # Get the paths of HAB1 and HAB6
            hab1_path = os.path.join(folder_name, 'HAB_1.0','2D')

            # Check if HAB1 and HAB6 exist
            if os.path.exists(hab1_path):
                hab1_path = sorted(glob.glob(os.path.join(hab1_path,'*.nii.gz')))

                # Create the datapoint
                datapoint = {
                    'image': hab1_path,                    
                    'attributes': row['age_y'] 
                }
                # Add the datapoint to the datalist
                datalist.append(datapoint)

    # Split the datalist into training and validation sets
    train_datalist, val_datalist = train_test_split(datalist, test_size=0.05, random_state=42,shuffle=False)
    return (train_datalist, val_datalist)

but I got the error when I try to load the data in batch in the 
orig_imgs, attr_gt = batch["image"].cuda(), batch["attributes"].cuda() of process_minibatch_grad()

  warnings.warn("monai.networks.blocks.Warp: Using PyTorch native grid_sample.")
Traceback (most recent call last):
  File "src/spatial-intensity-transforms/sitgan/train.py", line 37, in <module>
    main(args["random seed"], args)
  File "src/spatial-intensity-transforms/sitgan/train.py", line 26, in main
    train_starGAN(args, dataloaders=dataloaders)
  File "/mnt/src/spatial-intensity-transforms/sitgan/models/stargan.py", line 109, in train_model
    G_loss, DR_loss, example_outputs = process_minibatch_grad(
  File "/mnt/src/spatial-intensity-transforms/sitgan/models/stargan.py", line 44, in process_minibatch_grad
    orig_imgs, attr_gt = batch["image"].cuda(), batch["attributes"].cuda()
AttributeError: 'list' object has no attribute 'cuda'.

I assume there is something I have not done right in the get_datalist, I am trying to load the data exactly the way you possibly did, could you please have a look and see where I might go wrong, do you mind sharing an example of your dataloading also?

Warm thanks!

**Comment by clintonjwang** [comment]
You need to load the nifti yourself. The "image" key in datapoint should already be a tensor. You can use the nibabel package to load the nii.gz file as a numpy array, then convert to pytorch tensor.
